const seedTickets = [];
const config=window.MAGIC_ARCHIVE_CONFIG||{};
const hasSupabase=Boolean(config.supabaseUrl&&config.supabaseAnonKey&&window.supabase);
const db=hasSupabase?window.supabase.createClient(config.supabaseUrl,config.supabaseAnonKey):null;
let tickets=[],previewUrl="",activeTicket=null,activeTicketIndex=null,isTicketFlying=false;
const $=id=>document.getElementById(id);
const library=$("library"),cardField=$("cardField"),ticketCount=$("ticketCount"),dust=$("dust");
const ticketModal=$("ticketModal"),addModal=$("addModal"),modalImage=$("modalImage"),modalTitle=$("modalTitle"),modalDate=$("modalDate"),modalNote=$("modalNote"),modalTags=$("modalTags");
const ticketForm=$("ticketForm"),imageInput=$("ticketImage"),imagePreview=$("imagePreview"),uploadLabel=$("uploadLabel"),formStatus=$("formStatus"),saveTicket=$("saveTicket"),deleteTicketBtn=$("deleteTicketBtn"),deleteStatus=$("deleteStatus");
function escapeHtml(v=""){return String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function shortDate(v){if(!v)return"Memory";const d=new Date(v+(v.length===10?"T00:00:00":""));return Number.isNaN(d.getTime())?v:d.toLocaleDateString("en-GB",{day:"2-digit",month:"short"})}
function fullDate(t){return[t.date,t.location].filter(Boolean).join(" · ")}
function seeded(n,salt=0){const x=Math.sin((n+1)*9283.17+salt*71.33)*43758.5453;return x-Math.floor(x)}
function ensureMagicFlightStyles(){if($("magicFlightStyles"))return;const s=document.createElement("style");s.id="magicFlightStyles";s.textContent=`
.magic-flight{position:fixed;z-index:9999;pointer-events:none;transform-origin:center;will-change:transform,left,top,width,height,opacity;filter:drop-shadow(0 18px 28px rgba(0,0,0,.55)) drop-shadow(0 0 18px rgba(74,255,147,.7));border-radius:16px;overflow:visible}.magic-flight img{width:100%;height:100%;display:block;object-fit:cover;border-radius:16px;border:1px solid rgba(170,255,205,.55);box-shadow:0 0 20px rgba(72,255,143,.25),inset 0 0 0 1px rgba(255,255,255,.08)}
.magic-flight::before,.magic-flight::after{content:"";position:absolute;right:72%;top:48%;width:clamp(120px,24vw,420px);height:8px;transform-origin:right center;pointer-events:none;border-radius:999px;background:linear-gradient(90deg,transparent,rgba(40,255,125,.08) 18%,rgba(67,255,142,.65) 72%,rgba(196,255,217,.95));filter:blur(5px);box-shadow:0 0 12px rgba(44,255,126,.8),0 0 30px rgba(30,210,99,.55);opacity:.9}.magic-flight::after{width:clamp(180px,34vw,560px);height:2px;top:56%;filter:blur(1px);opacity:.75}
.magic-spark{position:fixed;z-index:9998;width:5px;height:5px;border-radius:50%;pointer-events:none;background:#a8ffc7;box-shadow:0 0 8px #54ff91,0 0 18px #35d974;animation:magicSpark .72s ease-out forwards}@keyframes magicSpark{to{transform:translate(var(--sx),var(--sy)) scale(.1);opacity:0}}
body.ticket-magic-open .ticket-card{transition:opacity .25s ease,filter .25s ease}body.ticket-magic-open .ticket-card:not(.magic-source){filter:brightness(.58) saturate(.7)}.ticket-card.magic-source{opacity:.12!important}
@media(prefers-reduced-motion:reduce){.magic-flight::before,.magic-flight::after{display:none!important}}
`;document.head.appendChild(s)}
ensureMagicFlightStyles();
function renderTickets(){
 ticketCount.textContent=tickets.length;const mobile=matchMedia("(max-width:820px)").matches,cols=mobile?2:5,rows=Math.max(1,Math.ceil(tickets.length/cols));const fieldHeight=mobile?Math.max(innerHeight-62,460+rows*155):Math.max(innerHeight-74,420+rows*118);library.style.minHeight=`${fieldHeight}px`;
 cardField.innerHTML=tickets.map((t,i)=>{const col=i%cols,row=Math.floor(i/cols),lane=(col+.5)/cols*100,x=Math.max(4,Math.min(92,lane+(seeded(i,1)-.5)*(mobile?18:12))),y=Math.max(18,Math.min(94,(210+row*(mobile?150:112)+(seeded(i,2)-.5)*70)/fieldHeight*100)),dx=Math.round((seeded(i,3)-.5)*(mobile?70:150)),dy=Math.round((seeded(i,4)-.5)*(mobile?85:120)),dx2=Math.round((seeded(i,7)-.5)*(mobile?55:110)),dy2=Math.round((seeded(i,8)-.5)*(mobile?65:95)),drift=(14+seeded(i,5)*14).toFixed(1),scale=(.78+seeded(i,6)*.30).toFixed(2),rot=(-8+seeded(i,9)*16).toFixed(1);return `<button class="ticket-card" style="left:${x}%;top:${y}%;--float-delay:-${(i*2.37)%17}s;--rot:${rot}deg;--dx:${dx}px;--dy:${dy}px;--dx2:${dx2}px;--dy2:${dy2}px;--drift:${drift}s;--card-scale:${scale}" data-index="${i}" aria-label="Mở vé ${escapeHtml(t.title)}"><span class="card-aura"></span><span class="card-frame"><img src="${escapeHtml(t.image)}" alt="${escapeHtml(t.title)}" loading="lazy"></span><span class="card-caption"><b>${escapeHtml(shortDate(t.date))}</b><small>${escapeHtml(t.title)}</small></span></button>`}).join("");
 cardField.querySelectorAll(".ticket-card").forEach(c=>c.addEventListener("click",()=>openTicket(Number(c.dataset.index),c)))
}
function localTickets(){try{return JSON.parse(localStorage.getItem("magicArchiveTickets")||"[]")}catch{return[]}}
function saveLocal(list){localStorage.setItem("magicArchiveTickets",JSON.stringify(list))}
async function loadTickets(){if(hasSupabase){const{data,error}=await db.from("tickets").select("*").order("created_at",{ascending:true});if(!error&&data){tickets=data.map(t=>({id:t.id,title:t.title,date:t.event_date||"",location:t.location||"",image:t.image_url,note:t.note||"",tags:t.tags||[],remote:true}))}else{console.error(error);tickets=[]}}else tickets=localTickets();renderTickets()}
function makeSparks(x,y,count=14){for(let i=0;i<count;i++){const p=document.createElement("i");p.className="magic-spark";p.style.left=`${x+(Math.random()-.5)*30}px`;p.style.top=`${y+(Math.random()-.5)*30}px`;p.style.setProperty("--sx",`${(Math.random()-.5)*120}px`);p.style.setProperty("--sy",`${(Math.random()-.5)*90}px`);p.style.animationDelay=`${Math.random()*.16}s`;document.body.appendChild(p);setTimeout(()=>p.remove(),1000)}}
function flyTicket(source,t,direction="in"){return new Promise(resolve=>{if(matchMedia("(prefers-reduced-motion:reduce)").matches){resolve();return}const sr=source.getBoundingClientRect(),targetW=Math.min(innerWidth*.54,560),ratio=sr.width/Math.max(sr.height,1),targetH=Math.min(innerHeight*.56,targetW/Math.max(ratio,.7)),end={left:(innerWidth-targetW)/2,top:(innerHeight-targetH)/2,width:targetW,height:targetH};const start={left:sr.left,top:sr.top,width:sr.width,height:sr.height};const a=direction==="in"?start:end,b=direction==="in"?end:start;const flyer=document.createElement("div");flyer.className="magic-flight";flyer.innerHTML=`<img src="${escapeHtml(t.image)}" alt="">`;Object.assign(flyer.style,{left:`${a.left}px`,top:`${a.top}px`,width:`${a.width}px`,height:`${a.height}px`,opacity:"1"});document.body.appendChild(flyer);const cx=a.left+a.width/2,cy=a.top+a.height/2;makeSparks(cx,cy,10);const dx=b.left-a.left,dy=b.top-a.top,curve=Math.max(80,Math.min(220,Math.abs(dx)*.28+80));const anim=flyer.animate([{transform:"translate3d(0,0,0) rotateZ(0deg) rotateY(0deg) scale(1)",offset:0},{transform:`translate3d(${dx*.38}px,${dy*.20-curve}px,0) rotateZ(${direction==="in"?'-14':'12'}deg) rotateY(${direction==="in"?'38':'-34'}deg) scale(${direction==="in"?'1.08':'.94'})`,offset:.34},{transform:`translate3d(${dx*.72}px,${dy*.68-curve*.38}px,0) rotateZ(${direction==="in"?'9':'-8'}deg) rotateY(${direction==="in"?'-22':'24'}deg) scale(${direction==="in"?'1.16':'.9'})`,offset:.72},{transform:`translate3d(${dx}px,${dy}px,0) rotateZ(0deg) rotateY(0deg) scale(1)`,offset:1}],{duration:direction==="in"?880:760,easing:"cubic-bezier(.18,.76,.22,1)",fill:"forwards"});let trailTimer=setInterval(()=>{const r=flyer.getBoundingClientRect();makeSparks(r.left+r.width*.25,r.top+r.height*.55,2)},95);anim.onfinish=()=>{clearInterval(trailTimer);const r=flyer.getBoundingClientRect();makeSparks(r.left+r.width/2,r.top+r.height/2,18);flyer.remove();resolve()}})}
async function openTicket(i,source){if(isTicketFlying)return;const t=tickets[i];if(!t)return;isTicketFlying=true;activeTicket=t;activeTicketIndex=i;source=source||cardField.querySelector(`[data-index="${i}"]`);source?.classList.add("magic-source");document.body.classList.add("ticket-magic-open");modalImage.src=t.image;modalImage.alt=t.title;modalTitle.textContent=t.title;modalDate.textContent=fullDate(t);modalNote.textContent=t.note||"Một ký ức concert được lưu trong thư viện.";modalTags.innerHTML=(t.tags||[]).map(tag=>`<span>${escapeHtml(tag)}</span>`).join("");deleteStatus.textContent="";deleteTicketBtn.hidden=!t.remote;if(source)await flyTicket(source,t,"in");ticketModal.classList.add("open");ticketModal.setAttribute("aria-hidden","false");document.body.classList.add("modal-open");source?.classList.remove("magic-source");isTicketFlying=false}
async function closeTicket(){if(!activeTicket||isTicketFlying){if(!activeTicket){ticketModal.classList.remove("open");ticketModal.setAttribute("aria-hidden","true")};return}isTicketFlying=true;const t=activeTicket,i=activeTicketIndex,source=cardField.querySelector(`[data-index="${i}"]`);ticketModal.classList.remove("open");ticketModal.setAttribute("aria-hidden","true");document.body.classList.remove("modal-open");source?.classList.add("magic-source");if(source)await flyTicket(source,t,"out");source?.classList.remove("magic-source");document.body.classList.remove("ticket-magic-open");activeTicket=null;activeTicketIndex=null;deleteStatus.textContent="";isTicketFlying=false}
function openAdd(){addModal.classList.add("open");addModal.setAttribute("aria-hidden","false");document.body.classList.add("modal-open");formStatus.textContent=hasSupabase?"":"Demo mode: vé mới hiện trên thiết bị này. Kết nối Supabase để mọi người cùng thấy."}
function closeAdd(){addModal.classList.remove("open");addModal.setAttribute("aria-hidden","true");document.body.classList.remove("modal-open")}
$("openAddTicket").addEventListener("click",openAdd);document.querySelectorAll("[data-close-ticket]").forEach(e=>e.addEventListener("click",closeTicket));document.querySelectorAll("[data-close-add]").forEach(e=>e.addEventListener("click",closeAdd));document.addEventListener("keydown",e=>{if(e.key==="Escape"){if(ticketModal.classList.contains("open"))closeTicket();else closeAdd()}});
imageInput.addEventListener("change",()=>{const f=imageInput.files?.[0];if(!f)return;if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(f);imagePreview.src=previewUrl;imagePreview.hidden=false;uploadLabel.textContent="Đổi ảnh"});
async function fileToDataUrl(file){return await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
async function createTicket(e){e.preventDefault();const file=imageInput.files?.[0];if(!file){formStatus.textContent="Chọn một ảnh vé trước nhé.";return}if(file.size>8*1024*1024){formStatus.textContent="Ảnh hơi lớn. Vui lòng chọn ảnh dưới 8 MB.";return}saveTicket.disabled=true;saveTicket.textContent="Saving…";formStatus.textContent="";const data={title:$("ticketTitle").value.trim(),event_date:$("ticketDate").value||null,location:$("ticketLocation").value.trim(),note:$("ticketNote").value.trim(),tags:$("ticketTags").value.split(",").map(x=>x.trim()).filter(Boolean)};try{if(hasSupabase){const ext=(file.name.split(".").pop()||"jpg").toLowerCase(),path=`${Date.now()}-${crypto.randomUUID()}.${ext}`;const{error:ue}=await db.storage.from(config.bucket||"ticket-images").upload(path,file,{contentType:file.type,upsert:false});if(ue)throw ue;const{data:pd}=db.storage.from(config.bucket||"ticket-images").getPublicUrl(path);const{error:ie}=await db.from("tickets").insert({...data,image_url:pd.publicUrl});if(ie)throw ie;await loadTickets()}else{const image=await fileToDataUrl(file),list=localTickets();list.push({id:crypto.randomUUID(),title:data.title,date:data.event_date||"",location:data.location,image,note:data.note,tags:data.tags});saveLocal(list);await loadTickets()}ticketForm.reset();imagePreview.hidden=true;uploadLabel.textContent="＋ Chọn ảnh vé";formStatus.textContent="Đã lưu ✦";setTimeout(closeAdd,500)}catch(err){console.error(err);formStatus.textContent=`Không lưu được: ${err.message||"unknown error"}`}finally{saveTicket.disabled=false;saveTicket.textContent="Save Ticket ✦"}}
ticketForm.addEventListener("submit",createTicket);
function storagePathFromPublicUrl(url=""){const marker=`/storage/v1/object/public/${config.bucket||"ticket-images"}/`,idx=url.indexOf(marker);return idx===-1?null:decodeURIComponent(url.slice(idx+marker.length))}
async function deleteActiveTicket(){const t=activeTicket;if(!t||!t.remote)return;if(!confirm(`Xóa vé “${t.title}”? Hành động này không thể hoàn tác.`))return;deleteTicketBtn.disabled=true;deleteTicketBtn.textContent="Deleting…";deleteStatus.textContent="";try{const{error:re}=await db.from("tickets").delete().eq("id",t.id);if(re)throw re;const path=storagePathFromPublicUrl(t.image);if(path){const{error:se}=await db.storage.from(config.bucket||"ticket-images").remove([path]);if(se)console.warn("Ticket row deleted, but image cleanup failed:",se)}ticketModal.classList.remove("open");document.body.classList.remove("modal-open","ticket-magic-open");activeTicket=null;activeTicketIndex=null;await loadTickets()}catch(err){console.error(err);deleteStatus.textContent=`Không xóa được: ${err.message||"unknown error"}`}finally{deleteTicketBtn.disabled=false;deleteTicketBtn.textContent="Delete Ticket"}}
deleteTicketBtn.addEventListener("click",deleteActiveTicket);
if(matchMedia("(pointer:fine)").matches)window.addEventListener("pointermove",e=>{const x=(e.clientX/innerWidth-.5)*2,y=(e.clientY/innerHeight-.5)*2;library.style.setProperty("--mx",x.toFixed(3));library.style.setProperty("--my",y.toFixed(3));document.querySelectorAll(".ticket-card").forEach((c,i)=>{const depth=3+(i%5)*2;c.style.marginLeft=`${x*depth}px`;c.style.marginTop=`${y*depth*.35}px`})},{passive:true});
for(let i=0;i<42;i++){const p=document.createElement("i");p.style.left=`${Math.random()*100}%`;p.style.top=`${Math.random()*110}%`;p.style.animationDuration=`${8+Math.random()*15}s`;p.style.animationDelay=`${-Math.random()*16}s`;p.style.setProperty("--drift",`${-40+Math.random()*80}px`);p.style.opacity=`${.15+Math.random()*.55}`;dust.appendChild(p)}
addEventListener("resize",()=>{clearTimeout(window.__ticketResize);window.__ticketResize=setTimeout(renderTickets,180)},{passive:true});
loadTickets();